#!/bin/bash
#SBATCH -J download_files
#SBATCH -N 1
#SBATCH -c 2
#SBATCH -t 24:00:00
#SBATCH --mem=10G
#SBATCH --mail-type=END
#SBATCH -o slurm/download_files-%j.out
#SBATCH -e slurm/download_files-%j.err
#SBATCH --mail-user=tasawwar_rahman@brown.edu

## This scripts downloads all the chipseq files

#Our Search Metadata

mkdir chipseq_data

# Sample List
samples=(
"https://www.encodeproject.org/metadata/?replicates.library.biosample.donor.organism.scientific_name=Drosophila+melanogaster&assay_slims=DNA+binding&assay_title=TF+ChIP-seq&biosample_ontology.term_name=whole+organism&assembly=dm6&files.file_type=bed+narrowPeak&files.file_type=bigWig&type=Experiment&files.analyses.status=released&files.preferred_default=true"
https://www.encodeproject.org/files/ENCFF506HQQ/@@download/ENCFF506HQQ.bed.gz
https://www.encodeproject.org/files/ENCFF709GMR/@@download/ENCFF709GMR.bed.gz
https://www.encodeproject.org/files/ENCFF051KYE/@@download/ENCFF051KYE.bigWig
https://www.encodeproject.org/files/ENCFF977XQR/@@download/ENCFF977XQR.bed.gz
https://www.encodeproject.org/files/ENCFF861SJC/@@download/ENCFF861SJC.bed.gz
https://www.encodeproject.org/files/ENCFF156RID/@@download/ENCFF156RID.bigWig
https://www.encodeproject.org/files/ENCFF706GRD/@@download/ENCFF706GRD.bigWig
https://www.encodeproject.org/files/ENCFF452FLE/@@download/ENCFF452FLE.bed.gz
https://www.encodeproject.org/files/ENCFF453RFL/@@download/ENCFF453RFL.bigWig
https://www.encodeproject.org/files/ENCFF383XJL/@@download/ENCFF383XJL.bed.gz
https://www.encodeproject.org/files/ENCFF036WSP/@@download/ENCFF036WSP.bed.gz
https://www.encodeproject.org/files/ENCFF581WGT/@@download/ENCFF581WGT.bigWig
https://www.encodeproject.org/files/ENCFF312VLQ/@@download/ENCFF312VLQ.bed.gz
https://www.encodeproject.org/files/ENCFF856IHL/@@download/ENCFF856IHL.bigWig
https://www.encodeproject.org/files/ENCFF245LSN/@@download/ENCFF245LSN.bed.gz
https://www.encodeproject.org/files/ENCFF370WUX/@@download/ENCFF370WUX.bigWig
https://www.encodeproject.org/files/ENCFF014LQA/@@download/ENCFF014LQA.bed.gz
https://www.encodeproject.org/files/ENCFF709AUX/@@download/ENCFF709AUX.bed.gz
https://www.encodeproject.org/files/ENCFF495SYP/@@download/ENCFF495SYP.bigWig
https://www.encodeproject.org/files/ENCFF949WTZ/@@download/ENCFF949WTZ.bigWig
https://www.encodeproject.org/files/ENCFF891MAL/@@download/ENCFF891MAL.bed.gz
https://www.encodeproject.org/files/ENCFF177ASD/@@download/ENCFF177ASD.bed.gz
https://www.encodeproject.org/files/ENCFF317LGW/@@download/ENCFF317LGW.bigWig
https://www.encodeproject.org/files/ENCFF582ZUS/@@download/ENCFF582ZUS.bigWig
https://www.encodeproject.org/files/ENCFF832HJB/@@download/ENCFF832HJB.bed.gz
https://www.encodeproject.org/files/ENCFF594VMN/@@download/ENCFF594VMN.bed.gz
https://www.encodeproject.org/files/ENCFF914PMB/@@download/ENCFF914PMB.bed.gz
https://www.encodeproject.org/files/ENCFF328PCV/@@download/ENCFF328PCV.bed.gz
https://www.encodeproject.org/files/ENCFF651AYT/@@download/ENCFF651AYT.bed.gz
https://www.encodeproject.org/files/ENCFF565HZT/@@download/ENCFF565HZT.bed.gz
https://www.encodeproject.org/files/ENCFF423XAX/@@download/ENCFF423XAX.bed.gz
https://www.encodeproject.org/files/ENCFF561KEC/@@download/ENCFF561KEC.bed.gz
https://www.encodeproject.org/files/ENCFF023KLC/@@download/ENCFF023KLC.bed.gz
https://www.encodeproject.org/files/ENCFF810IMH/@@download/ENCFF810IMH.bed.gz
https://www.encodeproject.org/files/ENCFF919JDR/@@download/ENCFF919JDR.bed.gz
https://www.encodeproject.org/files/ENCFF151TGF/@@download/ENCFF151TGF.bed.gz
https://www.encodeproject.org/files/ENCFF853CVK/@@download/ENCFF853CVK.bed.gz
https://www.encodeproject.org/files/ENCFF325LXH/@@download/ENCFF325LXH.bed.gz
https://www.encodeproject.org/files/ENCFF154NON/@@download/ENCFF154NON.bed.gz
https://www.encodeproject.org/files/ENCFF770JYR/@@download/ENCFF770JYR.bed.gz
https://www.encodeproject.org/files/ENCFF247NLT/@@download/ENCFF247NLT.bed.gz
https://www.encodeproject.org/files/ENCFF598JXU/@@download/ENCFF598JXU.bed.gz
https://www.encodeproject.org/files/ENCFF127TLY/@@download/ENCFF127TLY.bed.gz
https://www.encodeproject.org/files/ENCFF318OKO/@@download/ENCFF318OKO.bed.gz
https://www.encodeproject.org/files/ENCFF357EFX/@@download/ENCFF357EFX.bed.gz
https://www.encodeproject.org/files/ENCFF256VJZ/@@download/ENCFF256VJZ.bigWig
https://www.encodeproject.org/files/ENCFF667SWP/@@download/ENCFF667SWP.bed.gz
https://www.encodeproject.org/files/ENCFF358JCA/@@download/ENCFF358JCA.bigWig
https://www.encodeproject.org/files/ENCFF920PYA/@@download/ENCFF920PYA.bed.gz
https://www.encodeproject.org/files/ENCFF051RKM/@@download/ENCFF051RKM.bed.gz
https://www.encodeproject.org/files/ENCFF932ESA/@@download/ENCFF932ESA.bed.gz
https://www.encodeproject.org/files/ENCFF718YZD/@@download/ENCFF718YZD.bed.gz
https://www.encodeproject.org/files/ENCFF373TMZ/@@download/ENCFF373TMZ.bigWig
https://www.encodeproject.org/files/ENCFF896AOM/@@download/ENCFF896AOM.bed.gz
https://www.encodeproject.org/files/ENCFF801XUK/@@download/ENCFF801XUK.bed.gz
https://www.encodeproject.org/files/ENCFF097FNP/@@download/ENCFF097FNP.bed.gz
https://www.encodeproject.org/files/ENCFF747RSE/@@download/ENCFF747RSE.bed.gz
https://www.encodeproject.org/files/ENCFF364VSQ/@@download/ENCFF364VSQ.bigWig
https://www.encodeproject.org/files/ENCFF441AFD/@@download/ENCFF441AFD.bed.gz
https://www.encodeproject.org/files/ENCFF543EOX/@@download/ENCFF543EOX.bed.gz
https://www.encodeproject.org/files/ENCFF821KUJ/@@download/ENCFF821KUJ.bigWig
https://www.encodeproject.org/files/ENCFF200GCV/@@download/ENCFF200GCV.bed.gz
https://www.encodeproject.org/files/ENCFF623RDH/@@download/ENCFF623RDH.bed.gz
https://www.encodeproject.org/files/ENCFF412ERQ/@@download/ENCFF412ERQ.bed.gz
https://www.encodeproject.org/files/ENCFF698AVD/@@download/ENCFF698AVD.bed.gz
https://www.encodeproject.org/files/ENCFF574VKT/@@download/ENCFF574VKT.bed.gz
https://www.encodeproject.org/files/ENCFF571STC/@@download/ENCFF571STC.bed.gz
https://www.encodeproject.org/files/ENCFF566AND/@@download/ENCFF566AND.bed.gz
https://www.encodeproject.org/files/ENCFF480LXX/@@download/ENCFF480LXX.bed.gz
https://www.encodeproject.org/files/ENCFF279LCA/@@download/ENCFF279LCA.bed.gz
https://www.encodeproject.org/files/ENCFF453JHO/@@download/ENCFF453JHO.bed.gz
https://www.encodeproject.org/files/ENCFF575JGX/@@download/ENCFF575JGX.bed.gz
https://www.encodeproject.org/files/ENCFF629XNY/@@download/ENCFF629XNY.bed.gz
https://www.encodeproject.org/files/ENCFF346DAK/@@download/ENCFF346DAK.bed.gz
https://www.encodeproject.org/files/ENCFF199XFV/@@download/ENCFF199XFV.bed.gz
https://www.encodeproject.org/files/ENCFF291ITU/@@download/ENCFF291ITU.bed.gz
https://www.encodeproject.org/files/ENCFF310MNI/@@download/ENCFF310MNI.bed.gz
https://www.encodeproject.org/files/ENCFF121BWC/@@download/ENCFF121BWC.bed.gz
https://www.encodeproject.org/files/ENCFF370NSR/@@download/ENCFF370NSR.bed.gz
https://www.encodeproject.org/files/ENCFF400LCF/@@download/ENCFF400LCF.bed.gz
https://www.encodeproject.org/files/ENCFF732FWJ/@@download/ENCFF732FWJ.bed.gz
https://www.encodeproject.org/files/ENCFF111IYL/@@download/ENCFF111IYL.bed.gz
https://www.encodeproject.org/files/ENCFF510FWE/@@download/ENCFF510FWE.bed.gz
https://www.encodeproject.org/files/ENCFF924WZW/@@download/ENCFF924WZW.bed.gz
https://www.encodeproject.org/files/ENCFF188PRM/@@download/ENCFF188PRM.bed.gz
https://www.encodeproject.org/files/ENCFF096ZZY/@@download/ENCFF096ZZY.bed.gz
https://www.encodeproject.org/files/ENCFF194SDY/@@download/ENCFF194SDY.bed.gz
https://www.encodeproject.org/files/ENCFF123ODE/@@download/ENCFF123ODE.bed.gz
https://www.encodeproject.org/files/ENCFF935MTW/@@download/ENCFF935MTW.bed.gz
https://www.encodeproject.org/files/ENCFF101TBI/@@download/ENCFF101TBI.bed.gz
https://www.encodeproject.org/files/ENCFF271JUU/@@download/ENCFF271JUU.bed.gz
https://www.encodeproject.org/files/ENCFF488JBJ/@@download/ENCFF488JBJ.bed.gz
https://www.encodeproject.org/files/ENCFF740MEO/@@download/ENCFF740MEO.bed.gz
https://www.encodeproject.org/files/ENCFF794CQT/@@download/ENCFF794CQT.bed.gz
https://www.encodeproject.org/files/ENCFF983LSZ/@@download/ENCFF983LSZ.bed.gz
https://www.encodeproject.org/files/ENCFF880ZSE/@@download/ENCFF880ZSE.bed.gz
https://www.encodeproject.org/files/ENCFF904JNR/@@download/ENCFF904JNR.bed.gz
https://www.encodeproject.org/files/ENCFF838MFW/@@download/ENCFF838MFW.bed.gz
https://www.encodeproject.org/files/ENCFF980PCO/@@download/ENCFF980PCO.bed.gz
https://www.encodeproject.org/files/ENCFF653XNX/@@download/ENCFF653XNX.bed.gz
https://www.encodeproject.org/files/ENCFF662DTG/@@download/ENCFF662DTG.bigWig
https://www.encodeproject.org/files/ENCFF478ABN/@@download/ENCFF478ABN.bed.gz
https://www.encodeproject.org/files/ENCFF599WRH/@@download/ENCFF599WRH.bigWig
https://www.encodeproject.org/files/ENCFF378KSO/@@download/ENCFF378KSO.bed.gz
https://www.encodeproject.org/files/ENCFF926PGA/@@download/ENCFF926PGA.bigWig
https://www.encodeproject.org/files/ENCFF826POV/@@download/ENCFF826POV.bed.gz
https://www.encodeproject.org/files/ENCFF794EYO/@@download/ENCFF794EYO.bigWig
https://www.encodeproject.org/files/ENCFF713IWH/@@download/ENCFF713IWH.bed.gz
https://www.encodeproject.org/files/ENCFF127ZEN/@@download/ENCFF127ZEN.bed.gz
https://www.encodeproject.org/files/ENCFF937RLN/@@download/ENCFF937RLN.bed.gz
https://www.encodeproject.org/files/ENCFF799UIH/@@download/ENCFF799UIH.bed.gz
https://www.encodeproject.org/files/ENCFF068FFX/@@download/ENCFF068FFX.bed.gz
https://www.encodeproject.org/files/ENCFF951OJS/@@download/ENCFF951OJS.bigWig
https://www.encodeproject.org/files/ENCFF074INK/@@download/ENCFF074INK.bed.gz
https://www.encodeproject.org/files/ENCFF275OIZ/@@download/ENCFF275OIZ.bed.gz
https://www.encodeproject.org/files/ENCFF902XUL/@@download/ENCFF902XUL.bed.gz
https://www.encodeproject.org/files/ENCFF181KRX/@@download/ENCFF181KRX.bigWig
https://www.encodeproject.org/files/ENCFF433NIY/@@download/ENCFF433NIY.bed.gz
https://www.encodeproject.org/files/ENCFF796WOX/@@download/ENCFF796WOX.bed.gz
https://www.encodeproject.org/files/ENCFF789WVF/@@download/ENCFF789WVF.bed.gz
https://www.encodeproject.org/files/ENCFF294EYG/@@download/ENCFF294EYG.bed.gz
https://www.encodeproject.org/files/ENCFF113EDI/@@download/ENCFF113EDI.bigWig
https://www.encodeproject.org/files/ENCFF997FFC/@@download/ENCFF997FFC.bed.gz
https://www.encodeproject.org/files/ENCFF020VAN/@@download/ENCFF020VAN.bed.gz
https://www.encodeproject.org/files/ENCFF239YHI/@@download/ENCFF239YHI.bed.gz
https://www.encodeproject.org/files/ENCFF969GCU/@@download/ENCFF969GCU.bigWig
https://www.encodeproject.org/files/ENCFF140RPI/@@download/ENCFF140RPI.bed.gz
https://www.encodeproject.org/files/ENCFF076IKF/@@download/ENCFF076IKF.bed.gz
https://www.encodeproject.org/files/ENCFF988OCV/@@download/ENCFF988OCV.bigWig
https://www.encodeproject.org/files/ENCFF084RTW/@@download/ENCFF084RTW.bed.gz
https://www.encodeproject.org/files/ENCFF539ATG/@@download/ENCFF539ATG.bed.gz
https://www.encodeproject.org/files/ENCFF912TQD/@@download/ENCFF912TQD.bed.gz
https://www.encodeproject.org/files/ENCFF424KIM/@@download/ENCFF424KIM.bigWig
https://www.encodeproject.org/files/ENCFF699JSU/@@download/ENCFF699JSU.bed.gz
https://www.encodeproject.org/files/ENCFF321OSN/@@download/ENCFF321OSN.bed.gz
https://www.encodeproject.org/files/ENCFF147YIC/@@download/ENCFF147YIC.bed.gz
https://www.encodeproject.org/files/ENCFF004BZT/@@download/ENCFF004BZT.bed.gz
https://www.encodeproject.org/files/ENCFF767QWV/@@download/ENCFF767QWV.bed.gz
https://www.encodeproject.org/files/ENCFF442URR/@@download/ENCFF442URR.bed.gz
https://www.encodeproject.org/files/ENCFF055BXR/@@download/ENCFF055BXR.bed.gz
https://www.encodeproject.org/files/ENCFF998XPW/@@download/ENCFF998XPW.bed.gz
https://www.encodeproject.org/files/ENCFF600UCD/@@download/ENCFF600UCD.bed.gz
https://www.encodeproject.org/files/ENCFF373ZJR/@@download/ENCFF373ZJR.bed.gz
https://www.encodeproject.org/files/ENCFF475KCB/@@download/ENCFF475KCB.bigWig
https://www.encodeproject.org/files/ENCFF752YKB/@@download/ENCFF752YKB.bigWig
https://www.encodeproject.org/files/ENCFF301FCC/@@download/ENCFF301FCC.bed.gz
https://www.encodeproject.org/files/ENCFF977IWP/@@download/ENCFF977IWP.bigWig
https://www.encodeproject.org/files/ENCFF720KMA/@@download/ENCFF720KMA.bed.gz
https://www.encodeproject.org/files/ENCFF432EKX/@@download/ENCFF432EKX.bed.gz
https://www.encodeproject.org/files/ENCFF239GUJ/@@download/ENCFF239GUJ.bed.gz
https://www.encodeproject.org/files/ENCFF770GUN/@@download/ENCFF770GUN.bed.gz
https://www.encodeproject.org/files/ENCFF741JPG/@@download/ENCFF741JPG.bed.gz
https://www.encodeproject.org/files/ENCFF067SPH/@@download/ENCFF067SPH.bed.gz
https://www.encodeproject.org/files/ENCFF946QWD/@@download/ENCFF946QWD.bigWig
https://www.encodeproject.org/files/ENCFF770ZYJ/@@download/ENCFF770ZYJ.bed.gz
https://www.encodeproject.org/files/ENCFF948XNU/@@download/ENCFF948XNU.bigWig
https://www.encodeproject.org/files/ENCFF890HPZ/@@download/ENCFF890HPZ.bed.gz
https://www.encodeproject.org/files/ENCFF783RRU/@@download/ENCFF783RRU.bed.gz
https://www.encodeproject.org/files/ENCFF610AKH/@@download/ENCFF610AKH.bigWig
https://www.encodeproject.org/files/ENCFF102AJD/@@download/ENCFF102AJD.bed.gz
https://www.encodeproject.org/files/ENCFF743ABH/@@download/ENCFF743ABH.bed.gz
https://www.encodeproject.org/files/ENCFF891KQD/@@download/ENCFF891KQD.bigWig
https://www.encodeproject.org/files/ENCFF272HRN/@@download/ENCFF272HRN.bed.gz
https://www.encodeproject.org/files/ENCFF101LXN/@@download/ENCFF101LXN.bed.gz
https://www.encodeproject.org/files/ENCFF159JTG/@@download/ENCFF159JTG.bed.gz
https://www.encodeproject.org/files/ENCFF169ZEG/@@download/ENCFF169ZEG.bed.gz
https://www.encodeproject.org/files/ENCFF499UZV/@@download/ENCFF499UZV.bigWig
https://www.encodeproject.org/files/ENCFF621YOD/@@download/ENCFF621YOD.bed.gz
https://www.encodeproject.org/files/ENCFF582WMX/@@download/ENCFF582WMX.bed.gz
https://www.encodeproject.org/files/ENCFF256SLO/@@download/ENCFF256SLO.bed.gz
https://www.encodeproject.org/files/ENCFF502GLZ/@@download/ENCFF502GLZ.bed.gz
https://www.encodeproject.org/files/ENCFF965DLY/@@download/ENCFF965DLY.bed.gz
https://www.encodeproject.org/files/ENCFF920RXL/@@download/ENCFF920RXL.bed.gz
https://www.encodeproject.org/files/ENCFF916ZJW/@@download/ENCFF916ZJW.bed.gz
https://www.encodeproject.org/files/ENCFF814GSN/@@download/ENCFF814GSN.bed.gz
https://www.encodeproject.org/files/ENCFF992FNM/@@download/ENCFF992FNM.bed.gz
https://www.encodeproject.org/files/ENCFF621ZFI/@@download/ENCFF621ZFI.bed.gz
https://www.encodeproject.org/files/ENCFF591TQI/@@download/ENCFF591TQI.bed.gz
https://www.encodeproject.org/files/ENCFF048MUD/@@download/ENCFF048MUD.bed.gz
https://www.encodeproject.org/files/ENCFF630PTF/@@download/ENCFF630PTF.bed.gz
https://www.encodeproject.org/files/ENCFF846DBY/@@download/ENCFF846DBY.bed.gz
https://www.encodeproject.org/files/ENCFF195BCQ/@@download/ENCFF195BCQ.bed.gz
https://www.encodeproject.org/files/ENCFF163GOO/@@download/ENCFF163GOO.bed.gz
https://www.encodeproject.org/files/ENCFF030PPG/@@download/ENCFF030PPG.bed.gz
https://www.encodeproject.org/files/ENCFF835MUP/@@download/ENCFF835MUP.bed.gz
https://www.encodeproject.org/files/ENCFF821OGZ/@@download/ENCFF821OGZ.bed.gz
https://www.encodeproject.org/files/ENCFF477REP/@@download/ENCFF477REP.bed.gz
https://www.encodeproject.org/files/ENCFF470TDZ/@@download/ENCFF470TDZ.bed.gz
https://www.encodeproject.org/files/ENCFF323PJT/@@download/ENCFF323PJT.bed.gz
https://www.encodeproject.org/files/ENCFF118OVG/@@download/ENCFF118OVG.bed.gz
https://www.encodeproject.org/files/ENCFF305KHK/@@download/ENCFF305KHK.bed.gz
https://www.encodeproject.org/files/ENCFF256XYR/@@download/ENCFF256XYR.bigWig
https://www.encodeproject.org/files/ENCFF666ONW/@@download/ENCFF666ONW.bed.gz
https://www.encodeproject.org/files/ENCFF829QJB/@@download/ENCFF829QJB.bed.gz
https://www.encodeproject.org/files/ENCFF986EKN/@@download/ENCFF986EKN.bed.gz
https://www.encodeproject.org/files/ENCFF341GPU/@@download/ENCFF341GPU.bed.gz
https://www.encodeproject.org/files/ENCFF430LYD/@@download/ENCFF430LYD.bed.gz
https://www.encodeproject.org/files/ENCFF051GFC/@@download/ENCFF051GFC.bed.gz
https://www.encodeproject.org/files/ENCFF087NOZ/@@download/ENCFF087NOZ.bed.gz
https://www.encodeproject.org/files/ENCFF383MZV/@@download/ENCFF383MZV.bed.gz
https://www.encodeproject.org/files/ENCFF638OVH/@@download/ENCFF638OVH.bed.gz
https://www.encodeproject.org/files/ENCFF631OFN/@@download/ENCFF631OFN.bed.gz
https://www.encodeproject.org/files/ENCFF623NFB/@@download/ENCFF623NFB.bed.gz
https://www.encodeproject.org/files/ENCFF392ZEB/@@download/ENCFF392ZEB.bed.gz
https://www.encodeproject.org/files/ENCFF649JTF/@@download/ENCFF649JTF.bed.gz
https://www.encodeproject.org/files/ENCFF979FSE/@@download/ENCFF979FSE.bed.gz
https://www.encodeproject.org/files/ENCFF086AMT/@@download/ENCFF086AMT.bigWig
https://www.encodeproject.org/files/ENCFF180LHH/@@download/ENCFF180LHH.bed.gz
https://www.encodeproject.org/files/ENCFF108BXU/@@download/ENCFF108BXU.bed.gz
https://www.encodeproject.org/files/ENCFF200EWT/@@download/ENCFF200EWT.bed.gz
https://www.encodeproject.org/files/ENCFF934VQE/@@download/ENCFF934VQE.bed.gz
https://www.encodeproject.org/files/ENCFF115IAV/@@download/ENCFF115IAV.bed.gz
https://www.encodeproject.org/files/ENCFF816GGH/@@download/ENCFF816GGH.bed.gz
https://www.encodeproject.org/files/ENCFF794VOX/@@download/ENCFF794VOX.bed.gz
https://www.encodeproject.org/files/ENCFF761HCV/@@download/ENCFF761HCV.bed.gz
https://www.encodeproject.org/files/ENCFF276JYB/@@download/ENCFF276JYB.bed.gz
https://www.encodeproject.org/files/ENCFF972OON/@@download/ENCFF972OON.bed.gz
https://www.encodeproject.org/files/ENCFF138QKI/@@download/ENCFF138QKI.bed.gz
https://www.encodeproject.org/files/ENCFF100EUY/@@download/ENCFF100EUY.bed.gz
https://www.encodeproject.org/files/ENCFF357FPP/@@download/ENCFF357FPP.bed.gz
https://www.encodeproject.org/files/ENCFF982SDT/@@download/ENCFF982SDT.bed.gz
https://www.encodeproject.org/files/ENCFF523DZS/@@download/ENCFF523DZS.bed.gz
https://www.encodeproject.org/files/ENCFF894MXI/@@download/ENCFF894MXI.bed.gz
https://www.encodeproject.org/files/ENCFF446SME/@@download/ENCFF446SME.bed.gz
https://www.encodeproject.org/files/ENCFF827AXW/@@download/ENCFF827AXW.bed.gz
https://www.encodeproject.org/files/ENCFF842LET/@@download/ENCFF842LET.bed.gz
https://www.encodeproject.org/files/ENCFF377VXM/@@download/ENCFF377VXM.bed.gz
https://www.encodeproject.org/files/ENCFF216VTQ/@@download/ENCFF216VTQ.bed.gz
https://www.encodeproject.org/files/ENCFF967MPB/@@download/ENCFF967MPB.bed.gz
https://www.encodeproject.org/files/ENCFF231YVF/@@download/ENCFF231YVF.bed.gz
https://www.encodeproject.org/files/ENCFF266CND/@@download/ENCFF266CND.bed.gz
https://www.encodeproject.org/files/ENCFF110TIS/@@download/ENCFF110TIS.bed.gz
https://www.encodeproject.org/files/ENCFF185GRE/@@download/ENCFF185GRE.bed.gz
https://www.encodeproject.org/files/ENCFF250TYL/@@download/ENCFF250TYL.bed.gz
https://www.encodeproject.org/files/ENCFF308ZER/@@download/ENCFF308ZER.bed.gz
https://www.encodeproject.org/files/ENCFF412VYJ/@@download/ENCFF412VYJ.bed.gz
https://www.encodeproject.org/files/ENCFF190WOL/@@download/ENCFF190WOL.bed.gz
https://www.encodeproject.org/files/ENCFF845PRO/@@download/ENCFF845PRO.bed.gz
https://www.encodeproject.org/files/ENCFF461HQA/@@download/ENCFF461HQA.bed.gz
https://www.encodeproject.org/files/ENCFF486NKJ/@@download/ENCFF486NKJ.bed.gz
https://www.encodeproject.org/files/ENCFF367FBJ/@@download/ENCFF367FBJ.bed.gz
https://www.encodeproject.org/files/ENCFF372EFU/@@download/ENCFF372EFU.bed.gz
https://www.encodeproject.org/files/ENCFF173DOO/@@download/ENCFF173DOO.bed.gz
https://www.encodeproject.org/files/ENCFF537FQU/@@download/ENCFF537FQU.bed.gz
https://www.encodeproject.org/files/ENCFF964UDW/@@download/ENCFF964UDW.bed.gz
https://www.encodeproject.org/files/ENCFF500YBF/@@download/ENCFF500YBF.bed.gz
https://www.encodeproject.org/files/ENCFF736BHD/@@download/ENCFF736BHD.bed.gz
https://www.encodeproject.org/files/ENCFF688MZB/@@download/ENCFF688MZB.bed.gz
https://www.encodeproject.org/files/ENCFF892MVJ/@@download/ENCFF892MVJ.bed.gz
https://www.encodeproject.org/files/ENCFF474FPM/@@download/ENCFF474FPM.bed.gz
https://www.encodeproject.org/files/ENCFF515WFN/@@download/ENCFF515WFN.bed.gz
https://www.encodeproject.org/files/ENCFF921NGG/@@download/ENCFF921NGG.bed.gz
https://www.encodeproject.org/files/ENCFF783HST/@@download/ENCFF783HST.bed.gz
https://www.encodeproject.org/files/ENCFF392BMO/@@download/ENCFF392BMO.bed.gz
https://www.encodeproject.org/files/ENCFF796WLI/@@download/ENCFF796WLI.bed.gz
https://www.encodeproject.org/files/ENCFF184JDL/@@download/ENCFF184JDL.bed.gz
https://www.encodeproject.org/files/ENCFF161YYL/@@download/ENCFF161YYL.bed.gz
https://www.encodeproject.org/files/ENCFF148DCA/@@download/ENCFF148DCA.bed.gz
https://www.encodeproject.org/files/ENCFF865ORH/@@download/ENCFF865ORH.bed.gz
https://www.encodeproject.org/files/ENCFF532BBC/@@download/ENCFF532BBC.bed.gz
https://www.encodeproject.org/files/ENCFF427ZVV/@@download/ENCFF427ZVV.bed.gz
https://www.encodeproject.org/files/ENCFF729YEP/@@download/ENCFF729YEP.bed.gz
https://www.encodeproject.org/files/ENCFF008MOP/@@download/ENCFF008MOP.bed.gz
https://www.encodeproject.org/files/ENCFF704WGH/@@download/ENCFF704WGH.bed.gz
https://www.encodeproject.org/files/ENCFF388SSE/@@download/ENCFF388SSE.bed.gz
https://www.encodeproject.org/files/ENCFF659JOX/@@download/ENCFF659JOX.bed.gz
https://www.encodeproject.org/files/ENCFF038FQN/@@download/ENCFF038FQN.bed.gz
https://www.encodeproject.org/files/ENCFF847DMA/@@download/ENCFF847DMA.bed.gz
https://www.encodeproject.org/files/ENCFF166RHN/@@download/ENCFF166RHN.bed.gz
https://www.encodeproject.org/files/ENCFF144KSF/@@download/ENCFF144KSF.bed.gz
https://www.encodeproject.org/files/ENCFF661BQK/@@download/ENCFF661BQK.bed.gz
https://www.encodeproject.org/files/ENCFF765SPJ/@@download/ENCFF765SPJ.bed.gz
https://www.encodeproject.org/files/ENCFF634YIZ/@@download/ENCFF634YIZ.bed.gz
https://www.encodeproject.org/files/ENCFF042RUT/@@download/ENCFF042RUT.bed.gz
https://www.encodeproject.org/files/ENCFF066ODW/@@download/ENCFF066ODW.bed.gz
https://www.encodeproject.org/files/ENCFF602DII/@@download/ENCFF602DII.bed.gz
https://www.encodeproject.org/files/ENCFF735INH/@@download/ENCFF735INH.bed.gz
https://www.encodeproject.org/files/ENCFF801DWW/@@download/ENCFF801DWW.bed.gz
https://www.encodeproject.org/files/ENCFF060YZU/@@download/ENCFF060YZU.bed.gz
https://www.encodeproject.org/files/ENCFF588FVZ/@@download/ENCFF588FVZ.bed.gz
https://www.encodeproject.org/files/ENCFF107DOK/@@download/ENCFF107DOK.bed.gz
https://www.encodeproject.org/files/ENCFF675OTQ/@@download/ENCFF675OTQ.bed.gz
https://www.encodeproject.org/files/ENCFF830RFY/@@download/ENCFF830RFY.bed.gz
https://www.encodeproject.org/files/ENCFF999VZP/@@download/ENCFF999VZP.bed.gz
https://www.encodeproject.org/files/ENCFF572RAK/@@download/ENCFF572RAK.bigWig
https://www.encodeproject.org/files/ENCFF868TUK/@@download/ENCFF868TUK.bed.gz
https://www.encodeproject.org/files/ENCFF661TBC/@@download/ENCFF661TBC.bed.gz
https://www.encodeproject.org/files/ENCFF243MIA/@@download/ENCFF243MIA.bigWig
https://www.encodeproject.org/files/ENCFF755TOD/@@download/ENCFF755TOD.bed.gz
https://www.encodeproject.org/files/ENCFF603HCR/@@download/ENCFF603HCR.bed.gz
https://www.encodeproject.org/files/ENCFF910STC/@@download/ENCFF910STC.bed.gz
https://www.encodeproject.org/files/ENCFF463CYW/@@download/ENCFF463CYW.bigWig
https://www.encodeproject.org/files/ENCFF209SBW/@@download/ENCFF209SBW.bed.gz
https://www.encodeproject.org/files/ENCFF333ZPX/@@download/ENCFF333ZPX.bed.gz
https://www.encodeproject.org/files/ENCFF279DFN/@@download/ENCFF279DFN.bigWig
https://www.encodeproject.org/files/ENCFF221SOC/@@download/ENCFF221SOC.bed.gz
https://www.encodeproject.org/files/ENCFF546RHW/@@download/ENCFF546RHW.bed.gz
https://www.encodeproject.org/files/ENCFF753JMI/@@download/ENCFF753JMI.bed.gz
https://www.encodeproject.org/files/ENCFF565UBS/@@download/ENCFF565UBS.bed.gz
https://www.encodeproject.org/files/ENCFF267MOT/@@download/ENCFF267MOT.bed.gz
https://www.encodeproject.org/files/ENCFF087YEA/@@download/ENCFF087YEA.bed.gz
https://www.encodeproject.org/files/ENCFF849MDW/@@download/ENCFF849MDW.bigWig
https://www.encodeproject.org/files/ENCFF765VRD/@@download/ENCFF765VRD.bed.gz
https://www.encodeproject.org/files/ENCFF434KNT/@@download/ENCFF434KNT.bed.gz
https://www.encodeproject.org/files/ENCFF848BAO/@@download/ENCFF848BAO.bed.gz
https://www.encodeproject.org/files/ENCFF219HHO/@@download/ENCFF219HHO.bigWig
https://www.encodeproject.org/files/ENCFF544CSA/@@download/ENCFF544CSA.bed.gz
https://www.encodeproject.org/files/ENCFF250YXS/@@download/ENCFF250YXS.bed.gz
https://www.encodeproject.org/files/ENCFF554EFJ/@@download/ENCFF554EFJ.bigWig
https://www.encodeproject.org/files/ENCFF416EHO/@@download/ENCFF416EHO.bed.gz
https://www.encodeproject.org/files/ENCFF643DYI/@@download/ENCFF643DYI.bed.gz
https://www.encodeproject.org/files/ENCFF263EOD/@@download/ENCFF263EOD.bigWig
https://www.encodeproject.org/files/ENCFF949GGM/@@download/ENCFF949GGM.bed.gz
https://www.encodeproject.org/files/ENCFF017WWU/@@download/ENCFF017WWU.bed.gz
https://www.encodeproject.org/files/ENCFF145QEJ/@@download/ENCFF145QEJ.bed.gz
https://www.encodeproject.org/files/ENCFF104SSP/@@download/ENCFF104SSP.bed.gz
https://www.encodeproject.org/files/ENCFF381LPZ/@@download/ENCFF381LPZ.bed.gz
https://www.encodeproject.org/files/ENCFF267BPJ/@@download/ENCFF267BPJ.bed.gz
https://www.encodeproject.org/files/ENCFF707SCN/@@download/ENCFF707SCN.bed.gz
https://www.encodeproject.org/files/ENCFF757XFT/@@download/ENCFF757XFT.bed.gz
https://www.encodeproject.org/files/ENCFF186LXG/@@download/ENCFF186LXG.bed.gz
https://www.encodeproject.org/files/ENCFF330EPK/@@download/ENCFF330EPK.bed.gz
https://www.encodeproject.org/files/ENCFF679JMM/@@download/ENCFF679JMM.bed.gz
https://www.encodeproject.org/files/ENCFF641FRQ/@@download/ENCFF641FRQ.bed.gz
https://www.encodeproject.org/files/ENCFF571GHQ/@@download/ENCFF571GHQ.bed.gz
https://www.encodeproject.org/files/ENCFF040FQS/@@download/ENCFF040FQS.bed.gz
https://www.encodeproject.org/files/ENCFF528TAF/@@download/ENCFF528TAF.bed.gz
https://www.encodeproject.org/files/ENCFF143CSV/@@download/ENCFF143CSV.bed.gz
https://www.encodeproject.org/files/ENCFF240CXQ/@@download/ENCFF240CXQ.bed.gz
https://www.encodeproject.org/files/ENCFF561CUI/@@download/ENCFF561CUI.bed.gz
https://www.encodeproject.org/files/ENCFF572HME/@@download/ENCFF572HME.bed.gz
https://www.encodeproject.org/files/ENCFF477OLK/@@download/ENCFF477OLK.bed.gz
https://www.encodeproject.org/files/ENCFF090JJN/@@download/ENCFF090JJN.bed.gz
https://www.encodeproject.org/files/ENCFF934NUU/@@download/ENCFF934NUU.bed.gz
https://www.encodeproject.org/files/ENCFF148ZVZ/@@download/ENCFF148ZVZ.bed.gz
https://www.encodeproject.org/files/ENCFF430ZZC/@@download/ENCFF430ZZC.bed.gz
https://www.encodeproject.org/files/ENCFF752LCW/@@download/ENCFF752LCW.bed.gz
https://www.encodeproject.org/files/ENCFF603JQT/@@download/ENCFF603JQT.bed.gz
https://www.encodeproject.org/files/ENCFF548SKE/@@download/ENCFF548SKE.bed.gz
https://www.encodeproject.org/files/ENCFF730PDT/@@download/ENCFF730PDT.bed.gz
https://www.encodeproject.org/files/ENCFF688PWU/@@download/ENCFF688PWU.bed.gz
https://www.encodeproject.org/files/ENCFF417RHJ/@@download/ENCFF417RHJ.bed.gz
https://www.encodeproject.org/files/ENCFF826HKJ/@@download/ENCFF826HKJ.bigWig
https://www.encodeproject.org/files/ENCFF029ESV/@@download/ENCFF029ESV.bed.gz
https://www.encodeproject.org/files/ENCFF527SAZ/@@download/ENCFF527SAZ.bed.gz
https://www.encodeproject.org/files/ENCFF073WXU/@@download/ENCFF073WXU.bed.gz
https://www.encodeproject.org/files/ENCFF548MOC/@@download/ENCFF548MOC.bed.gz
https://www.encodeproject.org/files/ENCFF225IIQ/@@download/ENCFF225IIQ.bigWig
https://www.encodeproject.org/files/ENCFF424BZH/@@download/ENCFF424BZH.bed.gz
https://www.encodeproject.org/files/ENCFF820GXU/@@download/ENCFF820GXU.bed.gz
https://www.encodeproject.org/files/ENCFF318IJE/@@download/ENCFF318IJE.bed.gz
https://www.encodeproject.org/files/ENCFF242NCQ/@@download/ENCFF242NCQ.bed.gz
https://www.encodeproject.org/files/ENCFF826GMT/@@download/ENCFF826GMT.bed.gz
https://www.encodeproject.org/files/ENCFF837LOJ/@@download/ENCFF837LOJ.bigWig
https://www.encodeproject.org/files/ENCFF015ENX/@@download/ENCFF015ENX.bed.gz
https://www.encodeproject.org/files/ENCFF071SFB/@@download/ENCFF071SFB.bed.gz
https://www.encodeproject.org/files/ENCFF148CZG/@@download/ENCFF148CZG.bed.gz
https://www.encodeproject.org/files/ENCFF877HZB/@@download/ENCFF877HZB.bigWig
https://www.encodeproject.org/files/ENCFF651RRS/@@download/ENCFF651RRS.bed.gz
https://www.encodeproject.org/files/ENCFF287BIW/@@download/ENCFF287BIW.bed.gz
https://www.encodeproject.org/files/ENCFF235YVB/@@download/ENCFF235YVB.bigWig
https://www.encodeproject.org/files/ENCFF490KUD/@@download/ENCFF490KUD.bed.gz
https://www.encodeproject.org/files/ENCFF953BJP/@@download/ENCFF953BJP.bed.gz
https://www.encodeproject.org/files/ENCFF659WDZ/@@download/ENCFF659WDZ.bed.gz
https://www.encodeproject.org/files/ENCFF029NQZ/@@download/ENCFF029NQZ.bed.gz
https://www.encodeproject.org/files/ENCFF499KPW/@@download/ENCFF499KPW.bed.gz
https://www.encodeproject.org/files/ENCFF048JXD/@@download/ENCFF048JXD.bed.gz
https://www.encodeproject.org/files/ENCFF615QJY/@@download/ENCFF615QJY.bed.gz
https://www.encodeproject.org/files/ENCFF324NPH/@@download/ENCFF324NPH.bigWig
https://www.encodeproject.org/files/ENCFF356UHL/@@download/ENCFF356UHL.bed.gz
https://www.encodeproject.org/files/ENCFF892ONF/@@download/ENCFF892ONF.bed.gz
https://www.encodeproject.org/files/ENCFF512ALY/@@download/ENCFF512ALY.bed.gz
https://www.encodeproject.org/files/ENCFF208RWW/@@download/ENCFF208RWW.bigWig
https://www.encodeproject.org/files/ENCFF891GVS/@@download/ENCFF891GVS.bed.gz
https://www.encodeproject.org/files/ENCFF007ZEZ/@@download/ENCFF007ZEZ.bed.gz
https://www.encodeproject.org/files/ENCFF725HYD/@@download/ENCFF725HYD.bigWig
https://www.encodeproject.org/files/ENCFF633GLS/@@download/ENCFF633GLS.bed.gz
https://www.encodeproject.org/files/ENCFF037ZFI/@@download/ENCFF037ZFI.bed.gz
https://www.encodeproject.org/files/ENCFF322AHC/@@download/ENCFF322AHC.bed.gz
https://www.encodeproject.org/files/ENCFF113CFO/@@download/ENCFF113CFO.bigWig
https://www.encodeproject.org/files/ENCFF768WLW/@@download/ENCFF768WLW.bed.gz
https://www.encodeproject.org/files/ENCFF153OSN/@@download/ENCFF153OSN.bigWig
https://www.encodeproject.org/files/ENCFF167NJE/@@download/ENCFF167NJE.bed.gz
https://www.encodeproject.org/files/ENCFF186BCY/@@download/ENCFF186BCY.bigWig
https://www.encodeproject.org/files/ENCFF247KLE/@@download/ENCFF247KLE.bed.gz
https://www.encodeproject.org/files/ENCFF274ZTV/@@download/ENCFF274ZTV.bed.gz
https://www.encodeproject.org/files/ENCFF727BPQ/@@download/ENCFF727BPQ.bed.gz
https://www.encodeproject.org/files/ENCFF281TEO/@@download/ENCFF281TEO.bigWig
https://www.encodeproject.org/files/ENCFF026PTJ/@@download/ENCFF026PTJ.bed.gz
https://www.encodeproject.org/files/ENCFF859XVL/@@download/ENCFF859XVL.bigWig
https://www.encodeproject.org/files/ENCFF483SZJ/@@download/ENCFF483SZJ.bed.gz
https://www.encodeproject.org/files/ENCFF191EVG/@@download/ENCFF191EVG.bed.gz
https://www.encodeproject.org/files/ENCFF398WRM/@@download/ENCFF398WRM.bed.gz
https://www.encodeproject.org/files/ENCFF285HPB/@@download/ENCFF285HPB.bigWig
https://www.encodeproject.org/files/ENCFF555HLN/@@download/ENCFF555HLN.bed.gz
https://www.encodeproject.org/files/ENCFF167BXL/@@download/ENCFF167BXL.bed.gz
https://www.encodeproject.org/files/ENCFF236ZXL/@@download/ENCFF236ZXL.bed.gz
https://www.encodeproject.org/files/ENCFF742UIF/@@download/ENCFF742UIF.bed.gz
https://www.encodeproject.org/files/ENCFF101GPV/@@download/ENCFF101GPV.bigWig
https://www.encodeproject.org/files/ENCFF303AHH/@@download/ENCFF303AHH.bed.gz
https://www.encodeproject.org/files/ENCFF351KHY/@@download/ENCFF351KHY.bed.gz
https://www.encodeproject.org/files/ENCFF918PYW/@@download/ENCFF918PYW.bed.gz
https://www.encodeproject.org/files/ENCFF565AUW/@@download/ENCFF565AUW.bigWig
https://www.encodeproject.org/files/ENCFF624NYK/@@download/ENCFF624NYK.bed.gz
https://www.encodeproject.org/files/ENCFF941OPK/@@download/ENCFF941OPK.bed.gz
https://www.encodeproject.org/files/ENCFF851JXK/@@download/ENCFF851JXK.bigWig
https://www.encodeproject.org/files/ENCFF532VWU/@@download/ENCFF532VWU.bed.gz
https://www.encodeproject.org/files/ENCFF641DQO/@@download/ENCFF641DQO.bigWig
https://www.encodeproject.org/files/ENCFF249YBA/@@download/ENCFF249YBA.bed.gz
https://www.encodeproject.org/files/ENCFF341QUK/@@download/ENCFF341QUK.bed.gz
https://www.encodeproject.org/files/ENCFF755AJU/@@download/ENCFF755AJU.bed.gz
https://www.encodeproject.org/files/ENCFF049VBL/@@download/ENCFF049VBL.bigWig
https://www.encodeproject.org/files/ENCFF166ZSB/@@download/ENCFF166ZSB.bed.gz
https://www.encodeproject.org/files/ENCFF342BWT/@@download/ENCFF342BWT.bed.gz
https://www.encodeproject.org/files/ENCFF754QFL/@@download/ENCFF754QFL.bed.gz
https://www.encodeproject.org/files/ENCFF280ORF/@@download/ENCFF280ORF.bed.gz
https://www.encodeproject.org/files/ENCFF611QEL/@@download/ENCFF611QEL.bigWig
https://www.encodeproject.org/files/ENCFF695NUV/@@download/ENCFF695NUV.bed.gz
https://www.encodeproject.org/files/ENCFF836TXD/@@download/ENCFF836TXD.bed.gz
https://www.encodeproject.org/files/ENCFF912MDU/@@download/ENCFF912MDU.bigWig
https://www.encodeproject.org/files/ENCFF687LVK/@@download/ENCFF687LVK.bed.gz
https://www.encodeproject.org/files/ENCFF180GQT/@@download/ENCFF180GQT.bigWig
https://www.encodeproject.org/files/ENCFF237XXF/@@download/ENCFF237XXF.bed.gz
https://www.encodeproject.org/files/ENCFF030EXV/@@download/ENCFF030EXV.bigWig
https://www.encodeproject.org/files/ENCFF200VRC/@@download/ENCFF200VRC.bed.gz
https://www.encodeproject.org/files/ENCFF201DIS/@@download/ENCFF201DIS.bed.gz
https://www.encodeproject.org/files/ENCFF446QVN/@@download/ENCFF446QVN.bigWig
https://www.encodeproject.org/files/ENCFF078KWH/@@download/ENCFF078KWH.bed.gz
https://www.encodeproject.org/files/ENCFF060BTK/@@download/ENCFF060BTK.bed.gz
https://www.encodeproject.org/files/ENCFF991KUB/@@download/ENCFF991KUB.bigWig
https://www.encodeproject.org/files/ENCFF935MTF/@@download/ENCFF935MTF.bigWig
https://www.encodeproject.org/files/ENCFF478PEL/@@download/ENCFF478PEL.bed.gz
https://www.encodeproject.org/files/ENCFF495KPN/@@download/ENCFF495KPN.bigWig
https://www.encodeproject.org/files/ENCFF211AHY/@@download/ENCFF211AHY.bed.gz
https://www.encodeproject.org/files/ENCFF702ELY/@@download/ENCFF702ELY.bigWig
https://www.encodeproject.org/files/ENCFF137ATA/@@download/ENCFF137ATA.bed.gz
https://www.encodeproject.org/files/ENCFF362DVF/@@download/ENCFF362DVF.bigWig
https://www.encodeproject.org/files/ENCFF912HNG/@@download/ENCFF912HNG.bed.gz
https://www.encodeproject.org/files/ENCFF836ZQY/@@download/ENCFF836ZQY.bigWig
https://www.encodeproject.org/files/ENCFF386AJB/@@download/ENCFF386AJB.bed.gz
https://www.encodeproject.org/files/ENCFF916IVW/@@download/ENCFF916IVW.bed.gz
https://www.encodeproject.org/files/ENCFF787NDL/@@download/ENCFF787NDL.bed.gz
https://www.encodeproject.org/files/ENCFF045ELU/@@download/ENCFF045ELU.bed.gz
https://www.encodeproject.org/files/ENCFF725XMW/@@download/ENCFF725XMW.bed.gz
https://www.encodeproject.org/files/ENCFF760SXR/@@download/ENCFF760SXR.bed.gz
https://www.encodeproject.org/files/ENCFF508PWL/@@download/ENCFF508PWL.bed.gz
https://www.encodeproject.org/files/ENCFF897SXY/@@download/ENCFF897SXY.bed.gz
https://www.encodeproject.org/files/ENCFF658JCK/@@download/ENCFF658JCK.bed.gz
https://www.encodeproject.org/files/ENCFF076SSJ/@@download/ENCFF076SSJ.bed.gz
https://www.encodeproject.org/files/ENCFF295ECE/@@download/ENCFF295ECE.bed.gz
https://www.encodeproject.org/files/ENCFF823ZLI/@@download/ENCFF823ZLI.bed.gz
https://www.encodeproject.org/files/ENCFF932RYJ/@@download/ENCFF932RYJ.bed.gz
https://www.encodeproject.org/files/ENCFF102VYM/@@download/ENCFF102VYM.bed.gz
https://www.encodeproject.org/files/ENCFF774BTT/@@download/ENCFF774BTT.bigWig
https://www.encodeproject.org/files/ENCFF718MUX/@@download/ENCFF718MUX.bed.gz
https://www.encodeproject.org/files/ENCFF450TDM/@@download/ENCFF450TDM.bigWig
https://www.encodeproject.org/files/ENCFF228ZGS/@@download/ENCFF228ZGS.bed.gz
https://www.encodeproject.org/files/ENCFF881JXW/@@download/ENCFF881JXW.bigWig
https://www.encodeproject.org/files/ENCFF689PJF/@@download/ENCFF689PJF.bed.gz
https://www.encodeproject.org/files/ENCFF442EIL/@@download/ENCFF442EIL.bed.gz
https://www.encodeproject.org/files/ENCFF398LRM/@@download/ENCFF398LRM.bed.gz
https://www.encodeproject.org/files/ENCFF237FGY/@@download/ENCFF237FGY.bigWig
https://www.encodeproject.org/files/ENCFF098DVU/@@download/ENCFF098DVU.bed.gz
https://www.encodeproject.org/files/ENCFF849LEC/@@download/ENCFF849LEC.bed.gz
https://www.encodeproject.org/files/ENCFF052FGJ/@@download/ENCFF052FGJ.bigWig
https://www.encodeproject.org/files/ENCFF788KZW/@@download/ENCFF788KZW.bed.gz
https://www.encodeproject.org/files/ENCFF303PVS/@@download/ENCFF303PVS.bed.gz
https://www.encodeproject.org/files/ENCFF883ZPW/@@download/ENCFF883ZPW.bed.gz
https://www.encodeproject.org/files/ENCFF754IEL/@@download/ENCFF754IEL.bigWig
https://www.encodeproject.org/files/ENCFF127BGA/@@download/ENCFF127BGA.bed.gz
https://www.encodeproject.org/files/ENCFF924RRD/@@download/ENCFF924RRD.bed.gz
https://www.encodeproject.org/files/ENCFF833KTX/@@download/ENCFF833KTX.bigWig
https://www.encodeproject.org/files/ENCFF801WVY/@@download/ENCFF801WVY.bed.gz
https://www.encodeproject.org/files/ENCFF495XXK/@@download/ENCFF495XXK.bed.gz
https://www.encodeproject.org/files/ENCFF101MSP/@@download/ENCFF101MSP.bed.gz
https://www.encodeproject.org/files/ENCFF377XEQ/@@download/ENCFF377XEQ.bigWig
https://www.encodeproject.org/files/ENCFF172SKV/@@download/ENCFF172SKV.bed.gz
https://www.encodeproject.org/files/ENCFF977XMW/@@download/ENCFF977XMW.bed.gz
https://www.encodeproject.org/files/ENCFF244DJO/@@download/ENCFF244DJO.bigWig
https://www.encodeproject.org/files/ENCFF873THE/@@download/ENCFF873THE.bed.gz
https://www.encodeproject.org/files/ENCFF220JIS/@@download/ENCFF220JIS.bigWig
https://www.encodeproject.org/files/ENCFF991ZFV/@@download/ENCFF991ZFV.bed.gz
https://www.encodeproject.org/files/ENCFF499JRS/@@download/ENCFF499JRS.bed.gz
https://www.encodeproject.org/files/ENCFF384YLB/@@download/ENCFF384YLB.bigWig
https://www.encodeproject.org/files/ENCFF143WMU/@@download/ENCFF143WMU.bed.gz
https://www.encodeproject.org/files/ENCFF793RMH/@@download/ENCFF793RMH.bigWig
https://www.encodeproject.org/files/ENCFF420XLH/@@download/ENCFF420XLH.bed.gz
https://www.encodeproject.org/files/ENCFF838NYR/@@download/ENCFF838NYR.bigWig
https://www.encodeproject.org/files/ENCFF640EST/@@download/ENCFF640EST.bed.gz
https://www.encodeproject.org/files/ENCFF983ZBM/@@download/ENCFF983ZBM.bigWig
https://www.encodeproject.org/files/ENCFF271MAK/@@download/ENCFF271MAK.bed.gz
https://www.encodeproject.org/files/ENCFF158SZN/@@download/ENCFF158SZN.bed.gz
https://www.encodeproject.org/files/ENCFF051KNW/@@download/ENCFF051KNW.bigWig
https://www.encodeproject.org/files/ENCFF482DSB/@@download/ENCFF482DSB.bed.gz
https://www.encodeproject.org/files/ENCFF093RAU/@@download/ENCFF093RAU.bigWig
https://www.encodeproject.org/files/ENCFF885LOX/@@download/ENCFF885LOX.bed.gz
https://www.encodeproject.org/files/ENCFF939UBL/@@download/ENCFF939UBL.bigWig
https://www.encodeproject.org/files/ENCFF477LGQ/@@download/ENCFF477LGQ.bed.gz
https://www.encodeproject.org/files/ENCFF476RIG/@@download/ENCFF476RIG.bed.gz
https://www.encodeproject.org/files/ENCFF833KEG/@@download/ENCFF833KEG.bigWig
https://www.encodeproject.org/files/ENCFF705RND/@@download/ENCFF705RND.bed.gz
https://www.encodeproject.org/files/ENCFF610XIL/@@download/ENCFF610XIL.bigWig
https://www.encodeproject.org/files/ENCFF344KWT/@@download/ENCFF344KWT.bigWig
https://www.encodeproject.org/files/ENCFF185QUD/@@download/ENCFF185QUD.bed.gz
https://www.encodeproject.org/files/ENCFF489IJX/@@download/ENCFF489IJX.bigWig
https://www.encodeproject.org/files/ENCFF813LEG/@@download/ENCFF813LEG.bed.gz
https://www.encodeproject.org/files/ENCFF126SAC/@@download/ENCFF126SAC.bigWig
https://www.encodeproject.org/files/ENCFF472HIX/@@download/ENCFF472HIX.bed.gz
https://www.encodeproject.org/files/ENCFF576SES/@@download/ENCFF576SES.bed.gz
https://www.encodeproject.org/files/ENCFF911CHW/@@download/ENCFF911CHW.bigWig
https://www.encodeproject.org/files/ENCFF783MAP/@@download/ENCFF783MAP.bed.gz
https://www.encodeproject.org/files/ENCFF568JAR/@@download/ENCFF568JAR.bed.gz
https://www.encodeproject.org/files/ENCFF909ARP/@@download/ENCFF909ARP.bigWig
https://www.encodeproject.org/files/ENCFF771EVS/@@download/ENCFF771EVS.bed.gz
https://www.encodeproject.org/files/ENCFF718SBK/@@download/ENCFF718SBK.bigWig
https://www.encodeproject.org/files/ENCFF311CQG/@@download/ENCFF311CQG.bed.gz
https://www.encodeproject.org/files/ENCFF790ODK/@@download/ENCFF790ODK.bed.gz
https://www.encodeproject.org/files/ENCFF163PVV/@@download/ENCFF163PVV.bigWig
https://www.encodeproject.org/files/ENCFF662LYH/@@download/ENCFF662LYH.bigWig
https://www.encodeproject.org/files/ENCFF237BRY/@@download/ENCFF237BRY.bed.gz
https://www.encodeproject.org/files/ENCFF445UPE/@@download/ENCFF445UPE.bigWig
https://www.encodeproject.org/files/ENCFF982BYR/@@download/ENCFF982BYR.bed.gz
https://www.encodeproject.org/files/ENCFF545KPK/@@download/ENCFF545KPK.bed.gz
https://www.encodeproject.org/files/ENCFF873MSF/@@download/ENCFF873MSF.bed.gz
https://www.encodeproject.org/files/ENCFF885RDD/@@download/ENCFF885RDD.bed.gz
https://www.encodeproject.org/files/ENCFF919WHQ/@@download/ENCFF919WHQ.bed.gz
https://www.encodeproject.org/files/ENCFF861KLL/@@download/ENCFF861KLL.bed.gz
https://www.encodeproject.org/files/ENCFF499XZJ/@@download/ENCFF499XZJ.bed.gz
https://www.encodeproject.org/files/ENCFF722ZQI/@@download/ENCFF722ZQI.bed.gz
https://www.encodeproject.org/files/ENCFF230WNY/@@download/ENCFF230WNY.bigWig
https://www.encodeproject.org/files/ENCFF787VCT/@@download/ENCFF787VCT.bed.gz
https://www.encodeproject.org/files/ENCFF739TEK/@@download/ENCFF739TEK.bed.gz
https://www.encodeproject.org/files/ENCFF184JKU/@@download/ENCFF184JKU.bigWig
https://www.encodeproject.org/files/ENCFF319KMR/@@download/ENCFF319KMR.bed.gz
https://www.encodeproject.org/files/ENCFF519PAS/@@download/ENCFF519PAS.bigWig
https://www.encodeproject.org/files/ENCFF770IKE/@@download/ENCFF770IKE.bed.gz
https://www.encodeproject.org/files/ENCFF493QKD/@@download/ENCFF493QKD.bigWig
https://www.encodeproject.org/files/ENCFF565CZX/@@download/ENCFF565CZX.bed.gz
https://www.encodeproject.org/files/ENCFF115KVP/@@download/ENCFF115KVP.bed.gz
https://www.encodeproject.org/files/ENCFF484XIW/@@download/ENCFF484XIW.bed.gz
https://www.encodeproject.org/files/ENCFF036UDR/@@download/ENCFF036UDR.bed.gz
https://www.encodeproject.org/files/ENCFF443STM/@@download/ENCFF443STM.bigWig
https://www.encodeproject.org/files/ENCFF036VFX/@@download/ENCFF036VFX.bed.gz
https://www.encodeproject.org/files/ENCFF817UJJ/@@download/ENCFF817UJJ.bigWig
https://www.encodeproject.org/files/ENCFF588MKT/@@download/ENCFF588MKT.bigWig
https://www.encodeproject.org/files/ENCFF242ITJ/@@download/ENCFF242ITJ.bed.gz
https://www.encodeproject.org/files/ENCFF878WBZ/@@download/ENCFF878WBZ.bed.gz
https://www.encodeproject.org/files/ENCFF138QGO/@@download/ENCFF138QGO.bigWig
https://www.encodeproject.org/files/ENCFF638ANP/@@download/ENCFF638ANP.bed.gz
https://www.encodeproject.org/files/ENCFF319WUN/@@download/ENCFF319WUN.bed.gz
https://www.encodeproject.org/files/ENCFF739VKR/@@download/ENCFF739VKR.bigWig
https://www.encodeproject.org/files/ENCFF083WWE/@@download/ENCFF083WWE.bigWig
https://www.encodeproject.org/files/ENCFF736UQA/@@download/ENCFF736UQA.bed.gz
https://www.encodeproject.org/files/ENCFF651DKB/@@download/ENCFF651DKB.bigWig
https://www.encodeproject.org/files/ENCFF860IOU/@@download/ENCFF860IOU.bed.gz
https://www.encodeproject.org/files/ENCFF192QZI/@@download/ENCFF192QZI.bed.gz
https://www.encodeproject.org/files/ENCFF791MQP/@@download/ENCFF791MQP.bigWig
https://www.encodeproject.org/files/ENCFF376RKX/@@download/ENCFF376RKX.bed.gz
https://www.encodeproject.org/files/ENCFF074NWW/@@download/ENCFF074NWW.bed.gz
https://www.encodeproject.org/files/ENCFF893EGY/@@download/ENCFF893EGY.bed.gz
https://www.encodeproject.org/files/ENCFF478PLJ/@@download/ENCFF478PLJ.bed.gz
https://www.encodeproject.org/files/ENCFF930EJL/@@download/ENCFF930EJL.bigWig
https://www.encodeproject.org/files/ENCFF126QHB/@@download/ENCFF126QHB.bed.gz
https://www.encodeproject.org/files/ENCFF213LUC/@@download/ENCFF213LUC.bed.gz
https://www.encodeproject.org/files/ENCFF829DGO/@@download/ENCFF829DGO.bigWig
https://www.encodeproject.org/files/ENCFF267IYR/@@download/ENCFF267IYR.bed.gz
https://www.encodeproject.org/files/ENCFF452VQB/@@download/ENCFF452VQB.bigWig
https://www.encodeproject.org/files/ENCFF710XTO/@@download/ENCFF710XTO.bed.gz
https://www.encodeproject.org/files/ENCFF907QDT/@@download/ENCFF907QDT.bigWig
https://www.encodeproject.org/files/ENCFF963JIU/@@download/ENCFF963JIU.bed.gz
https://www.encodeproject.org/files/ENCFF069WPC/@@download/ENCFF069WPC.bed.gz
https://www.encodeproject.org/files/ENCFF051QKV/@@download/ENCFF051QKV.bed.gz
https://www.encodeproject.org/files/ENCFF727VIZ/@@download/ENCFF727VIZ.bigWig
https://www.encodeproject.org/files/ENCFF962CNO/@@download/ENCFF962CNO.bed.gz
https://www.encodeproject.org/files/ENCFF613KAV/@@download/ENCFF613KAV.bed.gz
https://www.encodeproject.org/files/ENCFF731VFB/@@download/ENCFF731VFB.bed.gz
https://www.encodeproject.org/files/ENCFF259VTW/@@download/ENCFF259VTW.bigWig
https://www.encodeproject.org/files/ENCFF923XAV/@@download/ENCFF923XAV.bed.gz
https://www.encodeproject.org/files/ENCFF013EPO/@@download/ENCFF013EPO.bed.gz
https://www.encodeproject.org/files/ENCFF553ZCC/@@download/ENCFF553ZCC.bigWig
https://www.encodeproject.org/files/ENCFF895AGK/@@download/ENCFF895AGK.bed.gz
https://www.encodeproject.org/files/ENCFF942MIL/@@download/ENCFF942MIL.bigWig
https://www.encodeproject.org/files/ENCFF598EOB/@@download/ENCFF598EOB.bed.gz
https://www.encodeproject.org/files/ENCFF831EUF/@@download/ENCFF831EUF.bed.gz
https://www.encodeproject.org/files/ENCFF787UIT/@@download/ENCFF787UIT.bigWig
https://www.encodeproject.org/files/ENCFF662KJL/@@download/ENCFF662KJL.bed.gz
https://www.encodeproject.org/files/ENCFF038DLA/@@download/ENCFF038DLA.bed.gz
https://www.encodeproject.org/files/ENCFF398HVZ/@@download/ENCFF398HVZ.bed.gz
https://www.encodeproject.org/files/ENCFF915KPO/@@download/ENCFF915KPO.bed.gz
https://www.encodeproject.org/files/ENCFF735IWA/@@download/ENCFF735IWA.bed.gz
https://www.encodeproject.org/files/ENCFF665ITW/@@download/ENCFF665ITW.bed.gz
https://www.encodeproject.org/files/ENCFF539PBL/@@download/ENCFF539PBL.bed.gz
https://www.encodeproject.org/files/ENCFF681NAI/@@download/ENCFF681NAI.bed.gz
https://www.encodeproject.org/files/ENCFF619NUF/@@download/ENCFF619NUF.bed.gz
https://www.encodeproject.org/files/ENCFF160SDR/@@download/ENCFF160SDR.bed.gz
https://www.encodeproject.org/files/ENCFF363ZZQ/@@download/ENCFF363ZZQ.bed.gz
https://www.encodeproject.org/files/ENCFF107PIZ/@@download/ENCFF107PIZ.bigWig
https://www.encodeproject.org/files/ENCFF927SDK/@@download/ENCFF927SDK.bed.gz
https://www.encodeproject.org/files/ENCFF814OVW/@@download/ENCFF814OVW.bed.gz
https://www.encodeproject.org/files/ENCFF622FZA/@@download/ENCFF622FZA.bed.gz
https://www.encodeproject.org/files/ENCFF947CQF/@@download/ENCFF947CQF.bigWig
https://www.encodeproject.org/files/ENCFF506RYX/@@download/ENCFF506RYX.bed.gz
https://www.encodeproject.org/files/ENCFF992KLH/@@download/ENCFF992KLH.bed.gz
https://www.encodeproject.org/files/ENCFF424INP/@@download/ENCFF424INP.bigWig
https://www.encodeproject.org/files/ENCFF723BQA/@@download/ENCFF723BQA.bigWig
https://www.encodeproject.org/files/ENCFF112YKE/@@download/ENCFF112YKE.bed.gz
https://www.encodeproject.org/files/ENCFF263LLY/@@download/ENCFF263LLY.bed.gz
https://www.encodeproject.org/files/ENCFF029EVO/@@download/ENCFF029EVO.bed.gz
https://www.encodeproject.org/files/ENCFF279QIR/@@download/ENCFF279QIR.bigWig
https://www.encodeproject.org/files/ENCFF978IXS/@@download/ENCFF978IXS.bed.gz
https://www.encodeproject.org/files/ENCFF159NQR/@@download/ENCFF159NQR.bigWig
https://www.encodeproject.org/files/ENCFF984TKT/@@download/ENCFF984TKT.bed.gz
https://www.encodeproject.org/files/ENCFF040RVF/@@download/ENCFF040RVF.bed.gz
https://www.encodeproject.org/files/ENCFF363VJY/@@download/ENCFF363VJY.bigWig
https://www.encodeproject.org/files/ENCFF703AHS/@@download/ENCFF703AHS.bed.gz
https://www.encodeproject.org/files/ENCFF569QEB/@@download/ENCFF569QEB.bed.gz
https://www.encodeproject.org/files/ENCFF422SIJ/@@download/ENCFF422SIJ.bed.gz
https://www.encodeproject.org/files/ENCFF631TNU/@@download/ENCFF631TNU.bed.gz
https://www.encodeproject.org/files/ENCFF379VFL/@@download/ENCFF379VFL.bigWig
https://www.encodeproject.org/files/ENCFF312FEZ/@@download/ENCFF312FEZ.bed.gz
https://www.encodeproject.org/files/ENCFF059RLX/@@download/ENCFF059RLX.bigWig
https://www.encodeproject.org/files/ENCFF754MJP/@@download/ENCFF754MJP.bed.gz
https://www.encodeproject.org/files/ENCFF274VMT/@@download/ENCFF274VMT.bigWig
https://www.encodeproject.org/files/ENCFF452IZW/@@download/ENCFF452IZW.bed.gz
https://www.encodeproject.org/files/ENCFF319IUM/@@download/ENCFF319IUM.bed.gz
https://www.encodeproject.org/files/ENCFF258CYK/@@download/ENCFF258CYK.bigWig
https://www.encodeproject.org/files/ENCFF184GQZ/@@download/ENCFF184GQZ.bed.gz
https://www.encodeproject.org/files/ENCFF078HQV/@@download/ENCFF078HQV.bigWig
https://www.encodeproject.org/files/ENCFF907UNN/@@download/ENCFF907UNN.bed.gz
https://www.encodeproject.org/files/ENCFF425IEU/@@download/ENCFF425IEU.bed.gz
https://www.encodeproject.org/files/ENCFF015BOI/@@download/ENCFF015BOI.bed.gz
https://www.encodeproject.org/files/ENCFF222UGR/@@download/ENCFF222UGR.bed.gz
https://www.encodeproject.org/files/ENCFF149KLC/@@download/ENCFF149KLC.bed.gz
https://www.encodeproject.org/files/ENCFF179OVA/@@download/ENCFF179OVA.bed.gz
https://www.encodeproject.org/files/ENCFF096TGQ/@@download/ENCFF096TGQ.bed.gz
https://www.encodeproject.org/files/ENCFF993AQH/@@download/ENCFF993AQH.bed.gz
https://www.encodeproject.org/files/ENCFF289GYP/@@download/ENCFF289GYP.bed.gz
https://www.encodeproject.org/files/ENCFF598JQB/@@download/ENCFF598JQB.bed.gz
https://www.encodeproject.org/files/ENCFF016AVO/@@download/ENCFF016AVO.bed.gz
https://www.encodeproject.org/files/ENCFF876TYA/@@download/ENCFF876TYA.bed.gz
https://www.encodeproject.org/files/ENCFF551ENE/@@download/ENCFF551ENE.bigWig
https://www.encodeproject.org/files/ENCFF249IFJ/@@download/ENCFF249IFJ.bed.gz
https://www.encodeproject.org/files/ENCFF954GVA/@@download/ENCFF954GVA.bed.gz
https://www.encodeproject.org/files/ENCFF763NMV/@@download/ENCFF763NMV.bigWig
https://www.encodeproject.org/files/ENCFF253CFP/@@download/ENCFF253CFP.bed.gz
https://www.encodeproject.org/files/ENCFF762PDV/@@download/ENCFF762PDV.bigWig
https://www.encodeproject.org/files/ENCFF648WIT/@@download/ENCFF648WIT.bed.gz
https://www.encodeproject.org/files/ENCFF249JPM/@@download/ENCFF249JPM.bigWig
https://www.encodeproject.org/files/ENCFF481ZNP/@@download/ENCFF481ZNP.bed.gz
https://www.encodeproject.org/files/ENCFF432MVY/@@download/ENCFF432MVY.bigWig
https://www.encodeproject.org/files/ENCFF921VCW/@@download/ENCFF921VCW.bed.gz
https://www.encodeproject.org/files/ENCFF290FGG/@@download/ENCFF290FGG.bigWig
https://www.encodeproject.org/files/ENCFF176EQP/@@download/ENCFF176EQP.bed.gz
https://www.encodeproject.org/files/ENCFF325GHA/@@download/ENCFF325GHA.bed.gz
https://www.encodeproject.org/files/ENCFF419DVZ/@@download/ENCFF419DVZ.bed.gz
https://www.encodeproject.org/files/ENCFF569VMC/@@download/ENCFF569VMC.bigWig
https://www.encodeproject.org/files/ENCFF746DXM/@@download/ENCFF746DXM.bed.gz
https://www.encodeproject.org/files/ENCFF102EKH/@@download/ENCFF102EKH.bigWig
https://www.encodeproject.org/files/ENCFF467VBC/@@download/ENCFF467VBC.bed.gz
https://www.encodeproject.org/files/ENCFF658JPF/@@download/ENCFF658JPF.bed.gz
https://www.encodeproject.org/files/ENCFF985CRM/@@download/ENCFF985CRM.bigWig
https://www.encodeproject.org/files/ENCFF371LSA/@@download/ENCFF371LSA.bed.gz
https://www.encodeproject.org/files/ENCFF528PGA/@@download/ENCFF528PGA.bigWig
https://www.encodeproject.org/files/ENCFF870HOI/@@download/ENCFF870HOI.bed.gz
https://www.encodeproject.org/files/ENCFF895AVT/@@download/ENCFF895AVT.bed.gz
https://www.encodeproject.org/files/ENCFF358XTE/@@download/ENCFF358XTE.bed.gz
https://www.encodeproject.org/files/ENCFF588ADP/@@download/ENCFF588ADP.bigWig
https://www.encodeproject.org/files/ENCFF109DAX/@@download/ENCFF109DAX.bed.gz
https://www.encodeproject.org/files/ENCFF922NXU/@@download/ENCFF922NXU.bed.gz
https://www.encodeproject.org/files/ENCFF393OSG/@@download/ENCFF393OSG.bed.gz
https://www.encodeproject.org/files/ENCFF829TYI/@@download/ENCFF829TYI.bigWig
https://www.encodeproject.org/files/ENCFF474GGC/@@download/ENCFF474GGC.bigWig
https://www.encodeproject.org/files/ENCFF716OGR/@@download/ENCFF716OGR.bed.gz
https://www.encodeproject.org/files/ENCFF526XYA/@@download/ENCFF526XYA.bigWig
https://www.encodeproject.org/files/ENCFF811IML/@@download/ENCFF811IML.bed.gz
https://www.encodeproject.org/files/ENCFF886CYZ/@@download/ENCFF886CYZ.bed.gz
https://www.encodeproject.org/files/ENCFF197YLX/@@download/ENCFF197YLX.bed.gz
https://www.encodeproject.org/files/ENCFF816HWP/@@download/ENCFF816HWP.bed.gz
https://www.encodeproject.org/files/ENCFF466GRZ/@@download/ENCFF466GRZ.bed.gz
https://www.encodeproject.org/files/ENCFF554AFK/@@download/ENCFF554AFK.bed.gz
https://www.encodeproject.org/files/ENCFF876ABI/@@download/ENCFF876ABI.bed.gz
https://www.encodeproject.org/files/ENCFF492JOY/@@download/ENCFF492JOY.bigWig
https://www.encodeproject.org/files/ENCFF591RHP/@@download/ENCFF591RHP.bed.gz
https://www.encodeproject.org/files/ENCFF793UWI/@@download/ENCFF793UWI.bigWig
https://www.encodeproject.org/files/ENCFF192OFW/@@download/ENCFF192OFW.bed.gz
https://www.encodeproject.org/files/ENCFF297PNE/@@download/ENCFF297PNE.bed.gz
https://www.encodeproject.org/files/ENCFF554HWG/@@download/ENCFF554HWG.bed.gz
https://www.encodeproject.org/files/ENCFF062RMX/@@download/ENCFF062RMX.bigWig
https://www.encodeproject.org/files/ENCFF401QAI/@@download/ENCFF401QAI.bed.gz
https://www.encodeproject.org/files/ENCFF284RTS/@@download/ENCFF284RTS.bed.gz
https://www.encodeproject.org/files/ENCFF126COV/@@download/ENCFF126COV.bed.gz
https://www.encodeproject.org/files/ENCFF403PHT/@@download/ENCFF403PHT.bigWig
https://www.encodeproject.org/files/ENCFF236CUV/@@download/ENCFF236CUV.bed.gz
https://www.encodeproject.org/files/ENCFF768OOM/@@download/ENCFF768OOM.bigWig
https://www.encodeproject.org/files/ENCFF377ILC/@@download/ENCFF377ILC.bed.gz
https://www.encodeproject.org/files/ENCFF679URO/@@download/ENCFF679URO.bed.gz
https://www.encodeproject.org/files/ENCFF682ROE/@@download/ENCFF682ROE.bed.gz
https://www.encodeproject.org/files/ENCFF643GNF/@@download/ENCFF643GNF.bed.gz
https://www.encodeproject.org/files/ENCFF724OZI/@@download/ENCFF724OZI.bed.gz
https://www.encodeproject.org/files/ENCFF266DFC/@@download/ENCFF266DFC.bed.gz
https://www.encodeproject.org/files/ENCFF501NEC/@@download/ENCFF501NEC.bed.gz
https://www.encodeproject.org/files/ENCFF899IHR/@@download/ENCFF899IHR.bed.gz
https://www.encodeproject.org/files/ENCFF404JNR/@@download/ENCFF404JNR.bed.gz
https://www.encodeproject.org/files/ENCFF386VVR/@@download/ENCFF386VVR.bed.gz
https://www.encodeproject.org/files/ENCFF502SLH/@@download/ENCFF502SLH.bed.gz
https://www.encodeproject.org/files/ENCFF282JPJ/@@download/ENCFF282JPJ.bed.gz
https://www.encodeproject.org/files/ENCFF989PRM/@@download/ENCFF989PRM.bigWig
https://www.encodeproject.org/files/ENCFF912NAE/@@download/ENCFF912NAE.bed.gz
https://www.encodeproject.org/files/ENCFF942UCD/@@download/ENCFF942UCD.bigWig
https://www.encodeproject.org/files/ENCFF358NDQ/@@download/ENCFF358NDQ.bed.gz
https://www.encodeproject.org/files/ENCFF893DNQ/@@download/ENCFF893DNQ.bigWig
https://www.encodeproject.org/files/ENCFF682JHE/@@download/ENCFF682JHE.bed.gz
https://www.encodeproject.org/files/ENCFF501IWX/@@download/ENCFF501IWX.bigWig
https://www.encodeproject.org/files/ENCFF441NFJ/@@download/ENCFF441NFJ.bed.gz
https://www.encodeproject.org/files/ENCFF869NVP/@@download/ENCFF869NVP.bigWig
https://www.encodeproject.org/files/ENCFF572AWU/@@download/ENCFF572AWU.bed.gz
https://www.encodeproject.org/files/ENCFF724QAO/@@download/ENCFF724QAO.bigWig
https://www.encodeproject.org/files/ENCFF907ZTO/@@download/ENCFF907ZTO.bed.gz
https://www.encodeproject.org/files/ENCFF568JXS/@@download/ENCFF568JXS.bigWig
https://www.encodeproject.org/files/ENCFF423HBJ/@@download/ENCFF423HBJ.bed.gz
https://www.encodeproject.org/files/ENCFF826FKA/@@download/ENCFF826FKA.bed.gz
https://www.encodeproject.org/files/ENCFF087GGV/@@download/ENCFF087GGV.bigWig
https://www.encodeproject.org/files/ENCFF955OIZ/@@download/ENCFF955OIZ.bed.gz
https://www.encodeproject.org/files/ENCFF433TRM/@@download/ENCFF433TRM.bed.gz
https://www.encodeproject.org/files/ENCFF069DQE/@@download/ENCFF069DQE.bed.gz
https://www.encodeproject.org/files/ENCFF513HGZ/@@download/ENCFF513HGZ.bed.gz
https://www.encodeproject.org/files/ENCFF471JEZ/@@download/ENCFF471JEZ.bed.gz
https://www.encodeproject.org/files/ENCFF343LZT/@@download/ENCFF343LZT.bed.gz
https://www.encodeproject.org/files/ENCFF773TZB/@@download/ENCFF773TZB.bed.gz
https://www.encodeproject.org/files/ENCFF518OMQ/@@download/ENCFF518OMQ.bed.gz
https://www.encodeproject.org/files/ENCFF834CPL/@@download/ENCFF834CPL.bed.gz
https://www.encodeproject.org/files/ENCFF874OMR/@@download/ENCFF874OMR.bigWig
https://www.encodeproject.org/files/ENCFF708ROQ/@@download/ENCFF708ROQ.bed.gz
https://www.encodeproject.org/files/ENCFF767KNY/@@download/ENCFF767KNY.bed.gz
https://www.encodeproject.org/files/ENCFF249OVZ/@@download/ENCFF249OVZ.bed.gz
https://www.encodeproject.org/files/ENCFF854XZI/@@download/ENCFF854XZI.bed.gz
https://www.encodeproject.org/files/ENCFF327QOB/@@download/ENCFF327QOB.bed.gz
https://www.encodeproject.org/files/ENCFF308OHV/@@download/ENCFF308OHV.bed.gz
https://www.encodeproject.org/files/ENCFF053UKP/@@download/ENCFF053UKP.bigWig
https://www.encodeproject.org/files/ENCFF201KQI/@@download/ENCFF201KQI.bed.gz
https://www.encodeproject.org/files/ENCFF745XNP/@@download/ENCFF745XNP.bed.gz
https://www.encodeproject.org/files/ENCFF449KQX/@@download/ENCFF449KQX.bed.gz
https://www.encodeproject.org/files/ENCFF602EKX/@@download/ENCFF602EKX.bigWig
https://www.encodeproject.org/files/ENCFF202YXL/@@download/ENCFF202YXL.bed.gz
https://www.encodeproject.org/files/ENCFF788IJB/@@download/ENCFF788IJB.bed.gz
https://www.encodeproject.org/files/ENCFF927MTH/@@download/ENCFF927MTH.bed.gz
https://www.encodeproject.org/files/ENCFF575EGM/@@download/ENCFF575EGM.bed.gz
https://www.encodeproject.org/files/ENCFF525XET/@@download/ENCFF525XET.bed.gz
https://www.encodeproject.org/files/ENCFF509CUV/@@download/ENCFF509CUV.bigWig
https://www.encodeproject.org/files/ENCFF307ETU/@@download/ENCFF307ETU.bigWig
https://www.encodeproject.org/files/ENCFF987FFV/@@download/ENCFF987FFV.bed.gz
https://www.encodeproject.org/files/ENCFF548KCT/@@download/ENCFF548KCT.bed.gz
https://www.encodeproject.org/files/ENCFF212MTQ/@@download/ENCFF212MTQ.bed.gz
https://www.encodeproject.org/files/ENCFF144OZH/@@download/ENCFF144OZH.bed.gz
https://www.encodeproject.org/files/ENCFF450KYU/@@download/ENCFF450KYU.bigWig
https://www.encodeproject.org/files/ENCFF278HWE/@@download/ENCFF278HWE.bed.gz
https://www.encodeproject.org/files/ENCFF841SUG/@@download/ENCFF841SUG.bigWig
https://www.encodeproject.org/files/ENCFF625ECQ/@@download/ENCFF625ECQ.bed.gz
https://www.encodeproject.org/files/ENCFF258JOT/@@download/ENCFF258JOT.bigWig
https://www.encodeproject.org/files/ENCFF899OBV/@@download/ENCFF899OBV.bed.gz
https://www.encodeproject.org/files/ENCFF524LOC/@@download/ENCFF524LOC.bed.gz
https://www.encodeproject.org/files/ENCFF143JCE/@@download/ENCFF143JCE.bigWig
https://www.encodeproject.org/files/ENCFF210CPN/@@download/ENCFF210CPN.bigWig
https://www.encodeproject.org/files/ENCFF516PXY/@@download/ENCFF516PXY.bed.gz
https://www.encodeproject.org/files/ENCFF534FQL/@@download/ENCFF534FQL.bed.gz
https://www.encodeproject.org/files/ENCFF403NLU/@@download/ENCFF403NLU.bigWig
https://www.encodeproject.org/files/ENCFF337BDK/@@download/ENCFF337BDK.bed.gz
https://www.encodeproject.org/files/ENCFF697VZN/@@download/ENCFF697VZN.bigWig
https://www.encodeproject.org/files/ENCFF421OZG/@@download/ENCFF421OZG.bigWig
https://www.encodeproject.org/files/ENCFF558OIU/@@download/ENCFF558OIU.bed.gz
https://www.encodeproject.org/files/ENCFF064RCS/@@download/ENCFF064RCS.bed.gz
https://www.encodeproject.org/files/ENCFF864MKA/@@download/ENCFF864MKA.bed.gz
https://www.encodeproject.org/files/ENCFF008SFA/@@download/ENCFF008SFA.bed.gz
https://www.encodeproject.org/files/ENCFF700NXM/@@download/ENCFF700NXM.bed.gz
https://www.encodeproject.org/files/ENCFF573GVG/@@download/ENCFF573GVG.bed.gz
https://www.encodeproject.org/files/ENCFF213RNS/@@download/ENCFF213RNS.bed.gz
https://www.encodeproject.org/files/ENCFF560ZBF/@@download/ENCFF560ZBF.bed.gz
https://www.encodeproject.org/files/ENCFF832SKZ/@@download/ENCFF832SKZ.bed.gz
https://www.encodeproject.org/files/ENCFF262VLK/@@download/ENCFF262VLK.bed.gz
https://www.encodeproject.org/files/ENCFF408JZT/@@download/ENCFF408JZT.bed.gz
https://www.encodeproject.org/files/ENCFF378LLQ/@@download/ENCFF378LLQ.bed.gz
https://www.encodeproject.org/files/ENCFF539BED/@@download/ENCFF539BED.bed.gz
https://www.encodeproject.org/files/ENCFF812AMG/@@download/ENCFF812AMG.bed.gz
https://www.encodeproject.org/files/ENCFF164WWT/@@download/ENCFF164WWT.bed.gz
https://www.encodeproject.org/files/ENCFF446GXF/@@download/ENCFF446GXF.bed.gz
https://www.encodeproject.org/files/ENCFF256ZXB/@@download/ENCFF256ZXB.bed.gz
https://www.encodeproject.org/files/ENCFF798IOJ/@@download/ENCFF798IOJ.bed.gz
https://www.encodeproject.org/files/ENCFF370XEC/@@download/ENCFF370XEC.bed.gz
https://www.encodeproject.org/files/ENCFF586YBO/@@download/ENCFF586YBO.bed.gz
https://www.encodeproject.org/files/ENCFF639EBZ/@@download/ENCFF639EBZ.bed.gz
https://www.encodeproject.org/files/ENCFF650YEL/@@download/ENCFF650YEL.bed.gz
https://www.encodeproject.org/files/ENCFF782AVC/@@download/ENCFF782AVC.bed.gz
https://www.encodeproject.org/files/ENCFF073ETO/@@download/ENCFF073ETO.bed.gz
https://www.encodeproject.org/files/ENCFF101AJI/@@download/ENCFF101AJI.bed.gz
https://www.encodeproject.org/files/ENCFF193JYL/@@download/ENCFF193JYL.bed.gz
https://www.encodeproject.org/files/ENCFF750DHO/@@download/ENCFF750DHO.bed.gz
https://www.encodeproject.org/files/ENCFF134DFH/@@download/ENCFF134DFH.bed.gz
https://www.encodeproject.org/files/ENCFF684MQZ/@@download/ENCFF684MQZ.bed.gz
https://www.encodeproject.org/files/ENCFF913ZLS/@@download/ENCFF913ZLS.bed.gz
https://www.encodeproject.org/files/ENCFF248QFM/@@download/ENCFF248QFM.bed.gz
https://www.encodeproject.org/files/ENCFF058MHE/@@download/ENCFF058MHE.bed.gz
https://www.encodeproject.org/files/ENCFF087YMD/@@download/ENCFF087YMD.bed.gz
https://www.encodeproject.org/files/ENCFF648COE/@@download/ENCFF648COE.bed.gz
https://www.encodeproject.org/files/ENCFF627TDV/@@download/ENCFF627TDV.bed.gz
https://www.encodeproject.org/files/ENCFF710XKN/@@download/ENCFF710XKN.bed.gz
https://www.encodeproject.org/files/ENCFF939PJL/@@download/ENCFF939PJL.bed.gz
https://www.encodeproject.org/files/ENCFF108OTF/@@download/ENCFF108OTF.bed.gz
https://www.encodeproject.org/files/ENCFF321QPN/@@download/ENCFF321QPN.bed.gz
https://www.encodeproject.org/files/ENCFF061FXA/@@download/ENCFF061FXA.bed.gz
https://www.encodeproject.org/files/ENCFF006VQI/@@download/ENCFF006VQI.bed.gz
https://www.encodeproject.org/files/ENCFF825MJJ/@@download/ENCFF825MJJ.bed.gz
https://www.encodeproject.org/files/ENCFF867MXB/@@download/ENCFF867MXB.bed.gz
https://www.encodeproject.org/files/ENCFF206SYO/@@download/ENCFF206SYO.bed.gz
https://www.encodeproject.org/files/ENCFF857BTR/@@download/ENCFF857BTR.bed.gz
https://www.encodeproject.org/files/ENCFF440RYZ/@@download/ENCFF440RYZ.bed.gz
https://www.encodeproject.org/files/ENCFF322BYQ/@@download/ENCFF322BYQ.bed.gz
https://www.encodeproject.org/files/ENCFF678MAP/@@download/ENCFF678MAP.bed.gz
https://www.encodeproject.org/files/ENCFF740TXB/@@download/ENCFF740TXB.bed.gz
https://www.encodeproject.org/files/ENCFF803TRO/@@download/ENCFF803TRO.bed.gz
https://www.encodeproject.org/files/ENCFF992OGZ/@@download/ENCFF992OGZ.bed.gz
https://www.encodeproject.org/files/ENCFF923TXP/@@download/ENCFF923TXP.bed.gz
https://www.encodeproject.org/files/ENCFF664CDO/@@download/ENCFF664CDO.bed.gz
https://www.encodeproject.org/files/ENCFF984YJS/@@download/ENCFF984YJS.bed.gz
https://www.encodeproject.org/files/ENCFF558RLK/@@download/ENCFF558RLK.bed.gz
https://www.encodeproject.org/files/ENCFF325UHA/@@download/ENCFF325UHA.bed.gz
https://www.encodeproject.org/files/ENCFF839UDC/@@download/ENCFF839UDC.bed.gz
https://www.encodeproject.org/files/ENCFF690LYQ/@@download/ENCFF690LYQ.bed.gz
https://www.encodeproject.org/files/ENCFF531YVL/@@download/ENCFF531YVL.bed.gz
https://www.encodeproject.org/files/ENCFF707GZA/@@download/ENCFF707GZA.bed.gz
https://www.encodeproject.org/files/ENCFF710HFR/@@download/ENCFF710HFR.bed.gz
https://www.encodeproject.org/files/ENCFF318MOC/@@download/ENCFF318MOC.bed.gz
https://www.encodeproject.org/files/ENCFF174FXW/@@download/ENCFF174FXW.bed.gz
https://www.encodeproject.org/files/ENCFF803IKO/@@download/ENCFF803IKO.bed.gz
https://www.encodeproject.org/files/ENCFF621JDK/@@download/ENCFF621JDK.bed.gz
https://www.encodeproject.org/files/ENCFF932JUB/@@download/ENCFF932JUB.bed.gz
https://www.encodeproject.org/files/ENCFF213TNU/@@download/ENCFF213TNU.bed.gz
https://www.encodeproject.org/files/ENCFF161YKX/@@download/ENCFF161YKX.bed.gz
https://www.encodeproject.org/files/ENCFF390FAE/@@download/ENCFF390FAE.bed.gz
https://www.encodeproject.org/files/ENCFF144TVZ/@@download/ENCFF144TVZ.bed.gz
https://www.encodeproject.org/files/ENCFF092HTT/@@download/ENCFF092HTT.bed.gz
https://www.encodeproject.org/files/ENCFF910NPG/@@download/ENCFF910NPG.bed.gz
https://www.encodeproject.org/files/ENCFF889JIG/@@download/ENCFF889JIG.bed.gz
https://www.encodeproject.org/files/ENCFF920ZZU/@@download/ENCFF920ZZU.bed.gz
https://www.encodeproject.org/files/ENCFF159BPU/@@download/ENCFF159BPU.bed.gz
https://www.encodeproject.org/files/ENCFF016EDE/@@download/ENCFF016EDE.bed.gz
https://www.encodeproject.org/files/ENCFF731KRI/@@download/ENCFF731KRI.bed.gz
https://www.encodeproject.org/files/ENCFF048PDV/@@download/ENCFF048PDV.bed.gz
https://www.encodeproject.org/files/ENCFF390CIX/@@download/ENCFF390CIX.bed.gz
https://www.encodeproject.org/files/ENCFF786FZV/@@download/ENCFF786FZV.bed.gz
https://www.encodeproject.org/files/ENCFF128YSX/@@download/ENCFF128YSX.bed.gz
https://www.encodeproject.org/files/ENCFF352QAJ/@@download/ENCFF352QAJ.bed.gz
https://www.encodeproject.org/files/ENCFF708VEF/@@download/ENCFF708VEF.bed.gz
https://www.encodeproject.org/files/ENCFF041EDI/@@download/ENCFF041EDI.bed.gz
https://www.encodeproject.org/files/ENCFF039NJX/@@download/ENCFF039NJX.bed.gz
https://www.encodeproject.org/files/ENCFF893XMO/@@download/ENCFF893XMO.bed.gz
https://www.encodeproject.org/files/ENCFF217GOU/@@download/ENCFF217GOU.bed.gz
https://www.encodeproject.org/files/ENCFF280NHA/@@download/ENCFF280NHA.bed.gz
https://www.encodeproject.org/files/ENCFF905ZFF/@@download/ENCFF905ZFF.bed.gz
https://www.encodeproject.org/files/ENCFF627TXO/@@download/ENCFF627TXO.bed.gz
https://www.encodeproject.org/files/ENCFF816LUA/@@download/ENCFF816LUA.bed.gz
https://www.encodeproject.org/files/ENCFF044NDZ/@@download/ENCFF044NDZ.bed.gz
https://www.encodeproject.org/files/ENCFF700EMX/@@download/ENCFF700EMX.bed.gz
https://www.encodeproject.org/files/ENCFF794HRO/@@download/ENCFF794HRO.bed.gz
https://www.encodeproject.org/files/ENCFF597SEX/@@download/ENCFF597SEX.bed.gz
https://www.encodeproject.org/files/ENCFF898EQO/@@download/ENCFF898EQO.bed.gz
https://www.encodeproject.org/files/ENCFF742LVH/@@download/ENCFF742LVH.bed.gz
https://www.encodeproject.org/files/ENCFF601ABX/@@download/ENCFF601ABX.bed.gz
https://www.encodeproject.org/files/ENCFF522ZND/@@download/ENCFF522ZND.bed.gz
https://www.encodeproject.org/files/ENCFF580OBO/@@download/ENCFF580OBO.bed.gz )

cd chipseq_data 

# Download all chipseq files from encode

for i in "${samples[@]}"
do
echo $i
wget $i
done

cd ..

#Move bigwigs to separate directory
#bigwigs are read pileups
cd chipseq_data
mkdir bigwig
mv *.bigWig bigwig

#Move bed files to their own directory
#Bed are peak calls
mkdir bed
mv *.bed.gz bed